import Fastify from 'fastify';
import bearerAuthPlugin from '@fastify/bearer-auth';
import Database from 'better-sqlite3';
import path from 'path';
import crypto from 'crypto';

const app = Fastify({ logger: true });

// Locate the shared desktop database safely
const storagePath = process.cwd().includes('packages') 
  ? path.join(process.cwd(), '../../apps/desktop') 
  : process.cwd();
const dbPath = path.join(storagePath, 'iris-offline.db');

const db = new Database(dbPath);

// Valid LIS-network token (generated by administrators in Settings)
const validTokens = new Set(['local-dev-token-xyz']);

app.register(bearerAuthPlugin, { keys: validTokens });

// D-9 Endpoint: Liveness check for LIS monitoring
app.get('/v1/health', async () => {
  return { status: 'ok', version: '1.1.0', mode: 'LIS-network' };
});

// D-9 Endpoint: LIS pushes patient/test context
app.post('/v1/patients/sync', async (request, reply) => {
  const { externalPatientId, name, dob, gender, testRequests } = request.body as any;

  if (!externalPatientId || !name) {
    return reply.status(400).send({
      type: 'invalid_request',
      title: 'Missing Required Fields',
      detail: 'externalPatientId and name are required.'
    });
  }

  try {
    const institution = db.prepare("SELECT id FROM institutions LIMIT 1").get() as any;
    if (!institution) throw new Error("Institution not configured in database.");

    const patientId = crypto.randomUUID();
    
    db.transaction(() => {
      // Create Patient
      db.prepare(`
        INSERT INTO patients (id, patient_code, institution_id, full_name, dob, gender, hospital_number, consent_given, consent_signature_path)
        VALUES (?, ?, ?, ?, ?, ?, ?, 1, 'lis-sync')
        ON CONFLICT(patient_code) DO NOTHING
      `).run(patientId, externalPatientId, institution.id, name, dob, gender, externalPatientId);

      // Create Sample and Tests
      const sampleId = crypto.randomUUID();
      db.prepare(`
        INSERT INTO samples (id, patient_id, institution_id, priority, status)
        VALUES (?, ?, ?, 'routine', 'requested')
      `).run(sampleId, patientId, institution.id);

      for (const test of testRequests) {
        db.prepare(`
          INSERT INTO test_requests (id, sample_id, test_category, test_name, status)
          VALUES (?, ?, 'parasitology', ?, 'requested')
        `).run(crypto.randomUUID(), sampleId, test.testType);
      }
    })();

    return { success: true, irisPatientId: patientId, message: "Patient and tests synced to local Worklist." };
  } catch (error: any) {
    app.log.error(error);
    return reply.status(500).send({ type: 'server_error', detail: error.message });
  }
});

// D-9 Endpoint: LIS pulls all approved results
app.get('/v1/results/:externalPatientId', async (request, reply) => {
  const { externalPatientId } = request.params as any;

  const results = db.prepare(`
    SELECT r.id, r.status, r.edited_findings, r.interpretive_comment, r.approved_at, r.verification_code,
           tr.test_name, u.full_name as approved_by_name
    FROM results r
    JOIN test_requests tr ON r.test_request_id = tr.id
    JOIN patients p ON r.patient_id = p.id
    LEFT JOIN users u ON r.approved_by = u.id
    WHERE p.patient_code = ? AND r.status = 'released'
  `).all(externalPatientId);

  if (!results.length) {
    return reply.status(404).send({ type: 'not_found', detail: 'No approved results found for this patient.' });
  }

  return { success: true, results };
});

// D-9 Endpoint: Test Mode Seeder (Development Only)
app.post('/v1/test/seed-synthetic-patient', async () => {
  const patientId = crypto.randomUUID();
  const sampleId = crypto.randomUUID();
  const inst = db.prepare("SELECT id FROM institutions LIMIT 1").get() as any;

  db.transaction(() => {
    db.prepare(`
      INSERT INTO patients (id, patient_code, institution_id, full_name, dob, gender, consent_given, consent_signature_path)
      VALUES (?, 'SYN-001', ?, 'Synthetic LIS Patient', '1990-01-01', 'Female', 1, 'mock')
    `).run(patientId, inst.id);

    db.prepare(`
      INSERT INTO samples (id, patient_id, institution_id, status) VALUES (?, ?, ?, 'requested')
    `).run(sampleId, patientId, inst.id);

    db.prepare(`
      INSERT INTO test_requests (id, sample_id, test_category, test_name, status)
      VALUES (?, ?, 'parasitology', 'Malaria Parasite', 'requested')
    `).run(crypto.randomUUID(), sampleId);
  })();

  return { success: true, irisPatientId: patientId };
});

// Start the server bound to 127.0.0.1 per the security requirement
const start = async () => {
  try {
    await app.listen({ port: 8787, host: '127.0.0.1' });
    console.log('LIS Integration API running at http://127.0.0.1:8787');
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};
start();